### PR TITLE
Color jittering + cutout transforms

### PR DESCRIPTION
**Pull request by alexrey88**
Two main changes:

- **New transforms for masker training**: Implement color jittering transforms (brightness, saturation, contrast) for training of the masker. 

Link for diff experiment ["m,s"]: [NewTransforms=ON vs NewTransforms=OFF](https://www.comet.ml/alexrey88/omnigan/873310e58c364aaca762f34a739e79fe/b9880431f5984442b54c19e98c0f2d78/compare?experiment-tab=images&groupBy=false&orderBy=desc&search=val_r_all&sortBy=name).

- **Differentiable transforms for painter training**: Color jittering + translation + cutout transforms are applied to our painter's generator output and our input for the discriminator update, and are also applied to our painter's generator output for the GAN loss part of the generator update (the transforms need to be differentiable for backpropagation in the generator). All functions were adapted from [_Data-Efficient GANs with DiffAugment_](https://github.com/mit-han-lab/data-efficient-gans/blob/master/DiffAugment_pytorch.py). 

Link for diff experiment ["p"]: [DiffAugm=ON vs DiffAugm=OFF](https://www.comet.ml/alexrey88/omnigan/f7ef63a24fea4812927d7efd1a0913e6/c80b72ae80f1492aacfbc07b1f1075dc/compare?experiment-tab=images&groupBy=false&imageId=cdb9e76561114f23be200b7156e3d5a3&orderBy=desc&search=val_rf&sortBy=step).

(Note: for now, if "m" and "p" are both in `opts.tasks`, the new transforms won't be apply to the input image for the training procedure, they will only be used for discriminator and generator updates of the painter. This is to avoid applying the transforms twice and giving a transformed image as input of the painter).

Visual results of the transforms:
val_r_s_10_#3_step_10

### CODE REVIEW

**Comment by vict0rsch** [comment]
https://hanlab.mit.edu/projects/data-efficient-gans/

**Comment by vict0rsch** [comment]
I don't think we'll be playing around that much with the diff transforms, can it just be a binary flag in opts.data? that would simplify the interface and the code.

What do you think?

**Comment by alexrey88** [comment]
@vict0rsch it's already an option in opts.gen.p.apply_diff_augment. You mean that it should be somemewhere else in our opts dict?

**Comment by vict0rsch** [comment]
Todo: use those transforms in wildfire instead of using PIL to speed up inference

**Pull request merged**
