### PR TITLE
fix deeplab encoder parameters + add number of params print in test

### PR DESCRIPTION
**Pull request by melisandeteng**
number of resblocks parameter wasn't propagating correctly in the code...

(it's a teeny-tiny pull request, but then we can keep track of where this problem came from)

### CODE REVIEW

**Comment by vict0rsch** [comment]
we really need to discuss this encoder, it's huge

**Comment by melisandeteng** [comment]
> we really need to discuss this encoder, it's huge

@vict0rsch  Actually if you remove the ResBlocks then it's "only" 42M parameters. If you add 1 resblock it goes up to 1000M !

**Comment by melisandeteng** [comment]
But I agree that the latent space is larger than what we are used to working with

**Comment by vict0rsch** [comment]
haha let's have a 100B param model like they do in NLP

**Comment by tianyu-z** [comment]
> haha let's have a 100B param model like they do in NLP

GPT-3 is crazy...no more needs for fine-tune Lol

**Pull request merged**
